[package]
name = "elf_parser"
version = "0.1.0"
authors = ["LeKillbit <lekillbit@example>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2"
enum-primitive-derive = "0.2.1"
file-utils = "0.1.5"
